version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "engine/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "training/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
