version: 2
updates:
  - package-ecosystem: cargo
    directories:
      - engine/
      - training/self-play/
    schedule:
      interval: monthly
    groups:
      rust-patch-updates:
        update-types:
          - patch
  - package-ecosystem: pip
    directory: training/
    schedule:
      interval: monthly
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
