style_edition = "2021"
max_width = 120
use_field_init_shorthand = true
# imports_granularity = "Module"
# format_code_in_doc_comments = true
# normalize_doc_attributes = true
# wrap_comments = true
# comment_width = 100
# format_strings = true
