%YAML 1.2
---
game: "hex4"
iterations: 75
device: auto
debug: false
working_area: "{CATTUS_TRAIN_TOP}/workarea/{GAME_NAME}"

model:
    base: "[none]"
    type: "ConvNetV1"
    residual_block_num: 7
    residual_filter_num: 16
    value_head_conv_output_channels_num: 16
    policy_head_conv_output_channels_num: 16

mcts:
    sim_num: 1400
    explore_factor: 1.41421
    prior_noise_alpha: 0.03
    prior_noise_epsilon: 0.25
    cache_size: 1000000

self_play:
    temperature_policy:
        - [8, 1.0]
        - [0.0]
    batch_size: 4
    games_num: 100
    threads: 8

training:
    latest_data_entries: 262144
    iteration_data_entries: 32768
    batch_size: 64
    learning_rate:
        - [25, 0.01]
        - [50, 0.001]
        - [0.0001]
    # l2reg: 0.0001
    use_train_data_across_runs: true

model_compare:
    temperature_policy:
        - [0.0]
    games_num: 30
    switching_winning_threshold: 0.55
    warning_losing_threshold: 0.55
    threads: 8

inference:
    engine: executorch
    backend: xnnpack
