game: "hex7"
iterations: 75
model_num: 8
debug: false
working_area: "{CATTUS_TRAIN_TOP}/workarea/{GAME_NAME}"

model:
    base: "[none]"
    type: "ConvNetV1"
    residual_block_num: 7
    residual_filter_num: 16
    value_head_conv_output_channels_num: 16
    policy_head_conv_output_channels_num: 16

engine:
    mcts:
        sim_num: 600
        explore_factor: 1.41421
        temperature_policy:
            - [9999, 0.0]
        prior_noise_alpha: 0.03
        prior_noise_epsilon: 0.25
        cache_size: 1000000
    model:
        batch_size: 8
        inference:
            engine: onnx-ort
    threads: 16

self_play:
    engine_overrides:
        mcts:
            temperature_policy:
                - [12, 1.0]
                - [9999, 0.0]
    games_num: 200
    model_compare:
        games_num: 32
        switching_winning_threshold: 0.55
        warning_losing_threshold: 0.55

training:
    latest_data_entries: 36864
    iteration_data_entries: 12288
    batch_size: 64
    learning_rate:
        - [25, 0.01]
        - [50, 0.001]
        - [0.0001]
    # l2reg: 0.0001
    use_train_data_across_runs: true
    device: null
