%YAML 1.2
---
game: "tictactoe"
working_area: "{CATTUS_TOP}/workarea/{GAME_NAME}"
mcts:
    sim_num: 140
    explore_factor: 1.41421
    prior_noise_alpha: 0.03
    prior_noise_epsilon: 0.25
    cache_size: 100000
self_play:
    iterations: 5
    temperature_policy:
        - [30,    1.0]
        - [       0.0]
    games_num: 100
    threads: 8
model:
    base: "[latest]"
    type: "ConvNetV1"
    residual_block_num: 2
    residual_filter_num: 2
    l2reg: 0.00005
training:
    latest_data_entries: 16384
    iteration_data_entries: 1024
    batch_size: 32
    learning_rate:
        - [40960, 0.01]
        - [61440, 0.001]
        - [       0.0001]
    compare:
        temperature_policy:
            - [       0.0]
        games_num: 20
        switching_winning_threshold: 0.55
        warning_losing_threshold: 0.55
        threads: 8
cpu: true
debug: false
