name: CI

on:
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  cattus:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      # Setup
      - name: Get repo
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          python-version: 3.12
          activate-environment: true
      - name: Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.89.0
          components: clippy
          cache-workspaces: engine
      - name: Install Python dependencies
        run: python etc/install_python_requirements.py

      # Build executorch
      - name: Cache Cpp ExecuTorch compiled libraries
        id: cache-executorch-build
        uses: actions/cache@v4
        with:
          path: engine/third-party/executorch/build/
          key: cache-executorch-build-${{ runner.OS }}-${{ hashFiles('engine/scripts/build_executorch.py') }}
      - name: Setup dev env, install executorch and its deps
        if: steps.cache-executorch-build.outputs.cache-hit != 'true'
        run: python engine/scripts/build_executorch.py

      # Build
      - name: Build Rust
        run: cargo build
        working-directory: engine

      # Linters
      - name: Rust Clippy linter
        uses: auguwu/clippy-action@1.4.0
        with:
          working-directory: engine
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Python Ruff linter
        uses: chartboost/ruff-action@v1
        with:
          args: check cattus-train

      # Tests
      - name: Rust tests
        run: cargo test
        working-directory: engine
      - name: Python tests
        run: pytest -s
        working-directory: cattus-train
