name: Development CI

on: push

permissions:
  contents: read

jobs:
  cattus:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
    # Setup
    - name: Get repo
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.77.0
        components: clippy
        cache-workspaces: cattus-engine
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e .
      working-directory: cattus-train

    # Build
    - name: Build Rust
      run: cargo build
      working-directory: cattus-engine

    # Linters
    - name: Rust Clippy linter
      uses: auguwu/clippy-action@1.3.0
      with:
        working-directory: cattus-engine
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Python Ruff linter
      uses: chartboost/ruff-action@v1
      with:
        args: cattus-train

    # Tests
    - name: Rust tests
      run: cargo test
      working-directory: cattus-engine
    - name: Python tests
      run: pytest -s
      working-directory: cattus-train
